// lib/dataMeeting.ts
import { Meeting, Department, Priority, Status, MeetingType } from "./types";

export const initialMeetingsData: Meeting[] = [
  {
    id: 1,
    title: "Rapat Evaluasi Produksi Q3",
    date: "2025-08-01",
    startTime: "09:00",
    endTime: "11:00",
    location: "Ruang Meeting Utama",
    organizer: "Budi Santoso",
    department: "Produksi",
    attendees: "Ahmad Rahman, Siti Nurhaliza, Dedi Kurniawan, Maya Sari",
    status: "completed",
    type: "offline",
    agenda:
      "Evaluasi target produksi, analisis kendala, dan strategi perbaikan untuk Q4",
    priority: "high",
    isRecurring: false,
    notulensi:
      "Hasil evaluasi: Target produksi Q3 tercapai 95%. Kendala utama: keterlambatan bahan baku dari supplier. Solusi: diversifikasi supplier dan meningkatkan buffer stock. Action items: 1) Tim procurement mencari 2 supplier alternatif (deadline: 15 Agustus), 2) Menyesuaikan jadwal produksi Q4 berdasarkan evaluasi.",
  },
  {
    id: 2,
    title: "Weekly Stand-up IT Team",
    date: "2025-08-01",
    startTime: "14:00",
    endTime: "15:00",
    location: "Google Meet",
    organizer: "Andi Wijaya",
    department: "IT",
    attendees: "Sarah Putri, Joko Widodo, Lisa Permata",
    status: "completed",
    type: "online",
    agenda:
      "Update progress proyek, diskusi blocker, dan planning sprint berikutnya",
    priority: "medium",
    isRecurring: true,
    meetingLink: "https://meet.google.com/abc-defg-hij",
    notulensi:
      "Progress: 1) Sarah - Module auth 80% complete, 2) Joko - API integration selesai, 3) Lisa - UI testing ongoing. Blocker: Database performance issue pada query report. Next sprint: Focus pada optimization dan bug fixes. Target deployment: 10 Agustus.",
  },
  {
    id: 3,
    title: "Presentasi Proposal Marketing Campaign",
    date: "2025-08-02",
    startTime: "10:30",
    endTime: "12:00",
    location: "Ruang Boardroom",
    organizer: "Dewi Sartika",
    department: "Marketing",
    attendees:
      "Bambang Suryanto, Nina Marlina, Rizki Pratama, Tina Wulandari, Hendra Gunawan",
    status: "scheduled",
    type: "offline",
    agenda:
      "Presentasi campaign Q4, review budget, dan approval timeline execution",
    priority: "high",
    isRecurring: false,
    attachments: "Campaign_Proposal_Q4.pdf, Budget_Analysis.xlsx",
    notulensi: "",
  },
  {
    id: 4,
    title: "Safety Meeting Bulanan",
    date: "2025-08-05",
    startTime: "08:00",
    endTime: "09:30",
    location: "Aula Lantai 2",
    organizer: "Ir. Soeparto",
    department: "HSE",
    attendees: "All Staff, Supervisors",
    status: "scheduled",
    type: "offline",
    agenda:
      "Review incident bulan lalu, update SOP keselamatan, dan training awareness",
    priority: "high",
    isRecurring: true,
    notulensi: "",
  },
  {
    id: 5,
    title: "Client Meeting - PT. Agro Mandiri",
    date: "2025-08-03",
    startTime: "13:00",
    endTime: "14:30",
    location: "Ruang VIP",
    organizer: "Ratna Sari",
    department: "Sales",
    attendees: "Direktur Sales, Account Manager, Client Representatives",
    status: "scheduled",
    type: "offline",
    agenda:
      "Negotiasi kontrak pupuk organik, diskusi volume dan pricing untuk 2025",
    priority: "high",
    isRecurring: false,
    notulensi: "",
  },
  {
    id: 6,
    title: "Training Keselamatan Kerja",
    date: "2025-08-06",
    startTime: "09:00",
    endTime: "11:00",
    location: "Ruang Training",
    organizer: "Dedi Kusuma",
    department: "HSE",
    attendees: "Karyawan Baru, Supervisor",
    status: "scheduled",
    type: "offline",
    agenda: "Pelatihan dasar K3, penggunaan APD, dan prosedur emergency",
    priority: "medium",
    isRecurring: false,
    notulensi: "",
  },
  {
    id: 7,
    title: "Review Budget Q4",
    date: "2025-08-07",
    startTime: "14:00",
    endTime: "16:00",
    location: "Zoom Meeting",
    organizer: "Finance Director",
    department: "Finance",
    attendees: "All Department Heads",
    status: "scheduled",
    type: "online",
    agenda:
      "Review anggaran Q4, alokasi budget per departemen, dan forecast 2026",
    priority: "high",
    isRecurring: false,
    notulensi: "",
  },
];

export const departments: Department[] = [
  "IT",
  "Produksi",
  "Marketing",
  "Sales",
  "HSE",
  "Finance",
  "HR",
];
export const priorities: Priority[] = ["low", "medium", "high"];
export const statuses: Status[] = [
  "scheduled",
  "ongoing",
  "completed",
  "cancelled",
];
export const meetingTypes: MeetingType[] = ["offline", "online"];
