// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import App from "next/app";
// import AppSidebar from "@/components/appsidebar";
// import Navbar from "@/components/navbar";
// import { ThemeProvider } from "@/components/provider/themeprovider";
// import { SidebarProvider } from "@/components/ui/sidebar";
// import { cookies } from "next/headers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const cookieStore = await cookies();
//   const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <SidebarProvider defaultOpen={defaultOpen}>
//             <AppSidebar />
//             <main className="w-full">
//               <Navbar />
//               <div className="px-2">{children}</div>
//             </main>
//           </SidebarProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/appsidebar";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/provider/themeprovider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function LayoutContent({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const isLoginPage = pathname === "/"; // karena login di page utama

  if (isLoginPage) {
    // Login page - no sidebar/navbar
    return <div className="w-full h-full">{children}</div>;
  }

  // Dashboard pages - with sidebar/navbar
  return (
    <SidebarProvider defaultOpen={true}>
      <AppSidebar />
      <main className="w-full">
        <Navbar />
        <div className="px-2">{children}</div>
      </main>
    </SidebarProvider>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LayoutContent>{children}</LayoutContent>
        </ThemeProvider>
      </body>
    </html>
  );
}
